### ISSUE TITLE
BrokenUserMap

### ISSUE THREAD

**Issue by rubensayshi** [gopherworks/bawt#8]
I got a `BrokerUserMap` about a week ago and I think since then the bot stopped being able to send DMs to people.

I'm wondering what this exactly means, unfortunately the only documentation on it is a comment above it:
```
		// We do some heavy logging here because this is troublesome
		// to find when it breaks and Slack breaks it by deprecating API's
```

maybe someone can shed some light on it and we can think of a solution to it (if this is really the problem?), I don't mind doing the work on it, just need to understand the issue first.

**Comment by mattouille** [comment]
Slack has probably deprecated another API. Here's the story to that:

Context: `github.com/nlopes/slack` is obviously not maintained by Slack.

1. Slack changes and breaks their API
2. This Slack package has to scramble to update the package
3. We then have to issue an update and release to use the newly released package API

What that comment is referring to is why the logging probably seems a bit more trace level, and it's because sometimes it's hard to figure out _what_ Slack broke.

I'll try and look through the nlopes changelog along with Slack and see if there's something I can find regarding user messaging.

**Comment by rubensayshi** [comment]
after a restart of the bot it was working fine again, from the surface it looks like the user IDs might have just changed for w/e reason.

**Comment by mattouille** [comment]
That is really interesting. I wasn't able to replicate it on my end but I'll keep this open in case it crops up again.

**Comment by rubensayshi** [comment]
does it sound plausable?

**Comment by mattouille** [comment]
It does, and we don't have a way to update a user ID if it changes for some reason. I'm not sure how or why a user ID would change, but it's certainly possible.

**Comment by rubensayshi** [comment]
FYI: was seeing the BrokenUserMap again, not sure if this was on the same path as the last time but with some added logging I figured out that this time at least it was from receiving messages from an incoming webhook we have setup for our gitlab commits, it has a blank user ID.

**Comment by mattouille** [comment]
Ah, I think I can add something in to fix that. Were you able to log the entire user struct? If not it's fine, I can get it recreated here.
